config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/build', to: 'scales#build'
  get '/generate_midi', to: 'scales#generate_midi'
  root to: 'scales#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  def show
    @notes = Scale::NOTES
    @types = Scale::TYPES

    @root = root || @notes.first
    @type = type || @types.first

    @scale = ScaleBuilder.build(@root, @type)
  end

  def build
    redirect_to action: :show, root: root, type: type
  end

  def generate_midi
    send_data(
      MidiBuilder.build_progression(root, type, params[:progression].to_i),
      filename: "#{root}#{type}_chord_progression.mid",
      type: 'audio/midi',
      disposition: 'attachment'
    )
  end

  private

  def root
    params[:root]
  end

  def type
    params[:type]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scales_helper.rb
module ScalesHelper
  def types_for_select(types)
    select = {}
    types.each do |t|
      select[t.to_s.titleize] = t
    end

    select
  end

  def key_class(key, scale_notes, scale_root)
    if key == scale_root
      'active-root'
    elsif scale_notes.include?(key)
      'active'
    else
      ''
    end
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>Scales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scales/_large_piano.html.erb
<ul class="piano set">
  <li class="key white c  <%= key_class(0, notes, root) %>"></li>
  <li class="key black cs <%= key_class(1, notes, root) %>"></li>
  <li class="key white d  <%= key_class(2, notes, root) %>"></li>
  <li class="key black ds <%= key_class(3, notes, root) %>"></li>
  <li class="key white e  <%= key_class(4, notes, root) %>"></li>
  <li class="key white f  <%= key_class(5, notes, root) %>"></li>
  <li class="key black fs <%= key_class(6, notes, root) %>"></li>
  <li class="key white g  <%= key_class(7, notes, root) %>"></li>
  <li class="key black gs <%= key_class(8, notes, root) %>"></li>
  <li class="key white a  <%= key_class(9, notes, root) %>"></li>
  <li class="key black as <%= key_class(10, notes, root) %>"></li>
  <li class="key white b  <%= key_class(11, notes, root) %>"></li>
</ul>

app/views/scales/_small_piano.html.erb
<ul class="piano set">
  <li class="key white sm c  <%= key_class(0, notes, root) %>"></li>
  <li class="key black sm cs <%= key_class(1, notes, root) %>"></li>
  <li class="key white sm d  <%= key_class(2, notes, root) %>"></li>
  <li class="key black sm ds <%= key_class(3, notes, root) %>"></li>
  <li class="key white sm e  <%= key_class(4, notes, root) %>"></li>
  <li class="key white sm f  <%= key_class(5, notes, root) %>"></li>
  <li class="key black sm fs <%= key_class(6, notes, root) %>"></li>
  <li class="key white sm g  <%= key_class(7, notes, root) %>"></li>
  <li class="key black sm gs <%= key_class(8, notes, root) %>"></li>
  <li class="key white sm a  <%= key_class(9, notes, root) %>"></li>
  <li class="key black sm as <%= key_class(10, notes, root) %>"></li>
  <li class="key white sm b  <%= key_class(11, notes, root) %>"></li>
</ul>

app/views/scales/show.html.erb
<div class="container main">
  <p class="title">Scales</p>
  <div class="row">
    <div class="column">
      <%= form_with(url: "/build", method: "post") do %>
        <div class="row row-responsive">
          <div class="column column-md-20 column-sm-50">
            <%= label_tag(@root, "Root:") %>
            <%= select_tag :root, options_for_select(@notes, @root) %>
          </div>
          <div class="column column-md-20 column-sm-50">
            <%= label_tag(:type, "Type:") %>
            <%= select_tag :type, options_for_select(types_for_select(@types), @type) %>
          </div>
        </div>
        <%= submit_tag("Generate") %>
      <% end %>
    </div>
  </div>

  <div class="row row-responsive">
    <div class="column column-md-50">
      <h2 class="scale-header">Notes</h2>
      <button class="scaleButton button-clear" data-notes='<%= @scale[:frequencies] %>'>
        <%= fa_icon "volume-up 3x" %>
      </button>
      <%= render partial: "large_piano", locals: { notes: @scale[:scale], root: @scale[:root] } %>
    </div>

    <% if @scale[:pentatonic].any? %>
      <div class="column column-md-50">
        <h2>Pentatonic</h2>
        <%= render partial: "large_piano", locals: { notes: @scale[:pentatonic], root: @scale[:root] } %>
      </div>
    <% end %>
  </div>

  <br/>

  <div class="row">
    <div class="column">
      <h2>Chords</h2>
      <% @scale[:chords].each_slice(4).to_a.each do |slice| %>
        <div class="row row-responsive">
          <% slice.each do |chord| %>
            <div class="column column-md-25 column-sm-50 column-xs-100">
              <h4>
                <strong><%= chord[:quality] %></strong>
                <%= "- #{chord[:name]}" %>
              </h4>
              <%= render partial: "small_piano", locals: { notes: chord[:notes], root: chord[:root] } %>
            </div>
          <% end %>
        </div>
        <br/>
      <% end %>
    </div>
  </div>

  <% if @scale[:progressions].any? %>
    <div class="row">
      <div class="column">
        <h2>Common Progressions</h2>
        <% @scale[:progressions].each_with_index do |progression, i| %>
          <div class="row row-responsive">
            <div class="column column-md-50 column-sm-60">
              <% progression.each_with_index do |chord, i| %>
                <p class="progression-chord"><%= chord[:quality] %></p>
              <% end %>
            </div>
            <div class="column column-md-50 column-sm-40">
              <button class="chordsButton button-clear progression-button" data-chords='<%= progression.map { |chord| chord[:frequencies] } %>'>
                <%= fa_icon "volume-up 2x" %>
              </button>
              <%= link_to(generate_midi_path(root: @root, type: @type, progression: i), target: "_self", 'data-no-turbolink' => true, class: "button button-clear progression-button") do %>
                <%= fa_icon "cloud-download 2x" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>
<% end %>
<br >
<footer class="footer">
  <section class="container">
    <div class="column">
      <p>Designed and built by
      <a href="http://wesdelp.com">Wes Delp</a>
      </p>
    </div>
  </section>
</footer>
</div>